### ISSUE TITLE
Android 10 will sleep while the RTSP-Player is fullscreen.

### ISSUE THREAD

**Issue by iesvme** [Huczeq/RTSP-Player#1]
Android 10 will sleep while the RTSP-Player is fullscreen.

**Comment by Huczeq** [comment]
Thank you for feedback,
I know this problem and it will be fixed in the next update.

Regards

**Comment by iesvme** [comment]
Thans! And I also hope to add an option of automatic horizontal screen when opening.

**Comment by iesvme** [comment]
> Thank you for feedback,
> I know this problem and it will be fixed in the next update.
> 
> Regards

**Comment by Huczeq** [comment]
Such functionality should appear in one of the future updates.
Thanks for the suggestions

**Comment by iesvme** [comment]
1.5 has been solution. Thank you very much!
