### ISSUE TITLE
Deteriorated sound quality

### ISSUE THREAD

**Issue by Ricky-Tigg** [Huczeq/RTSP-Player#15]
**version installed:** 1.7. **Latest version on this platform:** 1.7.1; thus the synchronization of this program's code with Google Play Store is not operational.

Hello. This application works properly.

Application [Audio Sharing](https://apps.gnome.org/fi/AudioSharing/), as flatpak format, operates as a RTSP server, itself served by Gstreamer. As the product name suggests, it only handles audio content.
```
$ lsof -i -n -P +c 0 | sed -n '/^COMMAND/ p; /(LISTEN)$/ p'
COMMAND          PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
audio-sharing  13157   (...)   13u  IPv4  77500      0t0  TCP *:8554 (LISTEN)
```
However the sound quality of the streamed content is deteriorated, and that despite there is only audio content to handle. It seems to me hardly possible to determine the component(s) at the root of this cause. Certainly, an improvement in this regard could be expected with the establishment of the upcoming [version 2.0 of the RTSP](https://www.rfc-editor.org/rfc/rfc7826), which is as a proposed standard and last updated in December 2016. For now, there is a unique version of it; 1.0; also here illustrated.
```
$ sudo tcpdump -vv -ttt -n -i wlp2s0 -c 8 src port 8554
(...)
 00:00:00.001937 IP (tos 0x0, ttl 64, id 44399, offset 0, flags [DF], proto TCP (6), length 253)
    192.168.100.197.rtsp-alt > 192.168.100.172.39770: Flags [P.], cksum 0x3fe4 (correct), seq 1:202, ack 131, win 249, options [nop,nop,TS val 1852248334 ecr 12353394], length 201: RTSP, length: 201
	RTSP/1.0 200 OK
	CSeq: 2
	Public: OPTIONS, DESCRIBE, ANNOUNCE, GET_PARAMETER, PAUSE, PLAY, RECORD, SETUP, SET_PARAMETER, TEARDOWN
	Server: GStreamer RTSP server
	Date: Tue, 23 Jan 2024 10:27:19 GMT
```
Also, maybe TCP or a component involved in the connection can be part of the cause. Won't guess whether the quality would be better via UDP.  Is there something you could propose me in order to investigate the cause?

**Comment by damianhoppe** [comment]
Hello.
Unfortunately, I don't use Linux, so I can't fully perform the tests.
To begin with, I suggest you verify your player. You can change the playback library from VLC to ExoPlayer in the RTSP-Player settings and test other applications, this will reduce the scope of the search.
Maybe it's a problem with RTSP-Player or the configuration of the audio streaming device, but honestly at this point I'm not sure what the problem might be.

I'll try to test Audio Sharing on a virtual machine, if the problem occurs with me too, I'll try to figure out what the problem might be.
You made me curious about the possibilities of Audio Sharing software.
It's just a pity that it's not available for other operating systems.

As soon as I determine something more I will contact you.

Kind regards,
Damian
