### ISSUE TITLE
Two tips about Reconnect and Mute

### ISSUE THREAD

**Issue by iesvme** [Huczeq/RTSP-Player#4]
Two tips:
1. Reconnect or manual can be automatic after disconnection of network.
2. Add button of mute or unmute in the player interface.

**Comment by Huczeq** [comment]
Thank you for the useful tips,

Kind regards,
Damian

**Comment by Huczeq** [comment]
Thank you for the useful tips,
This feature will definitely be implemented in future updates.

Kind regards,
Damian

**Comment by Huczeq** [comment]
Automatic reconnect has been added in the latest update (v1.5.2).

**Comment by iesvme** [comment]
I really appreciate for your help!

**Comment by Huczeq** [comment]
In the latest version (1.6.4) a button to mute and unmute sounds has been added.
